namespace Punto_De_Venta
{
    partial class frmReEdEmpleados
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmReEdEmpleados));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.materialPictureBox2 = new FontAwesome.Sharp.Material.MaterialPictureBox();
            this.lblUsuario = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuShapes1 = new Bunifu.UI.WinForms.BunifuShapes();
            this.txtApellidos = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtpFechaNacimiento = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuShapes2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.label2 = new System.Windows.Forms.Label();
            this.btnCerrar = new FontAwesome.Sharp.Material.MaterialButton();
            this.txtMunicipio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCalle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEstado = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPais = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShapes3 = new Bunifu.UI.WinForms.BunifuShapes();
            this.label3 = new System.Windows.Forms.Label();
            this.cboTurno = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cboRol = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtContrasena = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnGuardar = new FontAwesome.Sharp.Material.MaterialButton();
            this.bunifuElipse2 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btnCancelar = new FontAwesome.Sharp.Material.MaterialButton();
            this.bunifuElipse3 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.pictureEmpleado = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.materialPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEmpleado)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 20;
            this.bunifuElipse1.TargetControl = this;
            // 
            // materialPictureBox2
            // 
            this.materialPictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.materialPictureBox2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(39)))), ((int)(((byte)(35)))));
            this.materialPictureBox2.IconChar = FontAwesome.Sharp.MaterialIcons.AccountPlus;
            this.materialPictureBox2.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(39)))), ((int)(((byte)(35)))));
            this.materialPictureBox2.IconSize = 55;
            this.materialPictureBox2.Location = new System.Drawing.Point(332, 12);
            this.materialPictureBox2.Name = "materialPictureBox2";
            this.materialPictureBox2.Size = new System.Drawing.Size(55, 55);
            this.materialPictureBox2.TabIndex = 8;
            this.materialPictureBox2.TabStop = false;
            // 
            // lblUsuario
            // 
            this.lblUsuario.AutoSize = true;
            this.lblUsuario.BackColor = System.Drawing.Color.Transparent;
            this.lblUsuario.Font = new System.Drawing.Font("Segoe UI Black", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUsuario.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(39)))), ((int)(((byte)(35)))));
            this.lblUsuario.Location = new System.Drawing.Point(387, 17);
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.Size = new System.Drawing.Size(321, 41);
            this.lblUsuario.TabIndex = 7;
            this.lblUsuario.Text = "Registro de personal";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI Black", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label1.Location = new System.Drawing.Point(243, 95);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(155, 23);
            this.label1.TabIndex = 306;
            this.label1.Text = "Datos personales";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // bunifuShapes1
            // 
            this.bunifuShapes1.Angle = 0F;
            this.bunifuShapes1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes1.BorderThickness = 2;
            this.bunifuShapes1.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.FillShape = true;
            this.bunifuShapes1.Location = new System.Drawing.Point(247, 114);
            this.bunifuShapes1.Name = "bunifuShapes1";
            this.bunifuShapes1.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes1.Sides = 5;
            this.bunifuShapes1.Size = new System.Drawing.Size(765, 12);
            this.bunifuShapes1.TabIndex = 307;
            this.bunifuShapes1.Text = "bunifuShapes1";
            // 
            // txtApellidos
            // 
            this.txtApellidos.AcceptsReturn = false;
            this.txtApellidos.AcceptsTab = false;
            this.txtApellidos.AnimationSpeed = 200;
            this.txtApellidos.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtApellidos.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtApellidos.BackColor = System.Drawing.Color.Transparent;
            this.txtApellidos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtApellidos.BackgroundImage")));
            this.txtApellidos.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtApellidos.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtApellidos.BorderColorHover = System.Drawing.Color.Silver;
            this.txtApellidos.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtApellidos.BorderRadius = 20;
            this.txtApellidos.BorderThickness = 1;
            this.txtApellidos.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtApellidos.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidos.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtApellidos.DefaultText = "";
            this.txtApellidos.FillColor = System.Drawing.Color.White;
            this.txtApellidos.HideSelection = true;
            this.txtApellidos.IconLeft = null;
            this.txtApellidos.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidos.IconPadding = 10;
            this.txtApellidos.IconRight = null;
            this.txtApellidos.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidos.Lines = new string[0];
            this.txtApellidos.Location = new System.Drawing.Point(505, 140);
            this.txtApellidos.MaxLength = 32767;
            this.txtApellidos.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtApellidos.Modified = false;
            this.txtApellidos.Multiline = false;
            this.txtApellidos.Name = "txtApellidos";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidos.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtApellidos.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.Silver;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidos.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidos.OnIdleState = stateProperties40;
            this.txtApellidos.Padding = new System.Windows.Forms.Padding(3);
            this.txtApellidos.PasswordChar = '\0';
            this.txtApellidos.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtApellidos.PlaceholderText = "Apellidos";
            this.txtApellidos.ReadOnly = false;
            this.txtApellidos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtApellidos.SelectedText = "";
            this.txtApellidos.SelectionLength = 0;
            this.txtApellidos.SelectionStart = 0;
            this.txtApellidos.ShortcutsEnabled = true;
            this.txtApellidos.Size = new System.Drawing.Size(217, 43);
            this.txtApellidos.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtApellidos.TabIndex = 309;
            this.txtApellidos.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtApellidos.TextMarginBottom = 0;
            this.txtApellidos.TextMarginLeft = 3;
            this.txtApellidos.TextMarginTop = 0;
            this.txtApellidos.TextPlaceholder = "Apellidos";
            this.txtApellidos.UseSystemPasswordChar = false;
            this.txtApellidos.WordWrap = true;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.Silver;
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 20;
            this.txtNombre.BorderThickness = 1;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(247, 140);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.Silver;
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties44;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtNombre.PlaceholderText = "Nombre";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(217, 43);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 308;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 0;
            this.txtNombre.TextPlaceholder = "Nombre";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // dtpFechaNacimiento
            // 
            this.dtpFechaNacimiento.BackColor = System.Drawing.Color.Transparent;
            this.dtpFechaNacimiento.BorderRadius = 15;
            this.dtpFechaNacimiento.Color = System.Drawing.Color.Silver;
            this.dtpFechaNacimiento.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtpFechaNacimiento.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtpFechaNacimiento.DisabledColor = System.Drawing.Color.Gray;
            this.dtpFechaNacimiento.DisplayWeekNumbers = false;
            this.dtpFechaNacimiento.DPHeight = 0;
            this.dtpFechaNacimiento.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtpFechaNacimiento.FillDatePicker = false;
            this.dtpFechaNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtpFechaNacimiento.ForeColor = System.Drawing.Color.Black;
            this.dtpFechaNacimiento.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpFechaNacimiento.Icon = ((System.Drawing.Image)(resources.GetObject("dtpFechaNacimiento.Icon")));
            this.dtpFechaNacimiento.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.dtpFechaNacimiento.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtpFechaNacimiento.LeftTextMargin = 5;
            this.dtpFechaNacimiento.Location = new System.Drawing.Point(764, 140);
            this.dtpFechaNacimiento.MinimumSize = new System.Drawing.Size(4, 43);
            this.dtpFechaNacimiento.Name = "dtpFechaNacimiento";
            this.dtpFechaNacimiento.Size = new System.Drawing.Size(220, 43);
            this.dtpFechaNacimiento.TabIndex = 310;
            // 
            // bunifuShapes2
            // 
            this.bunifuShapes2.Angle = 0F;
            this.bunifuShapes2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes2.BorderThickness = 2;
            this.bunifuShapes2.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.FillShape = true;
            this.bunifuShapes2.Location = new System.Drawing.Point(247, 222);
            this.bunifuShapes2.Name = "bunifuShapes2";
            this.bunifuShapes2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes2.Sides = 5;
            this.bunifuShapes2.Size = new System.Drawing.Size(765, 12);
            this.bunifuShapes2.TabIndex = 312;
            this.bunifuShapes2.Text = "bunifuShapes2";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Segoe UI Black", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label2.Location = new System.Drawing.Point(243, 203);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(185, 23);
            this.label2.TabIndex = 311;
            this.label2.Text = "Ubicación y contacto";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnCerrar
            // 
            this.btnCerrar.FlatAppearance.BorderSize = 0;
            this.btnCerrar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCerrar.IconChar = FontAwesome.Sharp.MaterialIcons.WindowClose;
            this.btnCerrar.IconColor = System.Drawing.Color.Black;
            this.btnCerrar.IconSize = 38;
            this.btnCerrar.Location = new System.Drawing.Point(991, 17);
            this.btnCerrar.Name = "btnCerrar";
            this.btnCerrar.Size = new System.Drawing.Size(35, 36);
            this.btnCerrar.TabIndex = 313;
            this.btnCerrar.UseVisualStyleBackColor = true;
            this.btnCerrar.Click += new System.EventHandler(this.btnCerrar_Click);
            // 
            // txtMunicipio
            // 
            this.txtMunicipio.AcceptsReturn = false;
            this.txtMunicipio.AcceptsTab = false;
            this.txtMunicipio.AnimationSpeed = 200;
            this.txtMunicipio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMunicipio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMunicipio.BackColor = System.Drawing.Color.Transparent;
            this.txtMunicipio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMunicipio.BackgroundImage")));
            this.txtMunicipio.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtMunicipio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMunicipio.BorderColorHover = System.Drawing.Color.Silver;
            this.txtMunicipio.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMunicipio.BorderRadius = 20;
            this.txtMunicipio.BorderThickness = 1;
            this.txtMunicipio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMunicipio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMunicipio.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMunicipio.DefaultText = "";
            this.txtMunicipio.FillColor = System.Drawing.Color.White;
            this.txtMunicipio.HideSelection = true;
            this.txtMunicipio.IconLeft = null;
            this.txtMunicipio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMunicipio.IconPadding = 10;
            this.txtMunicipio.IconRight = null;
            this.txtMunicipio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMunicipio.Lines = new string[0];
            this.txtMunicipio.Location = new System.Drawing.Point(505, 257);
            this.txtMunicipio.MaxLength = 32767;
            this.txtMunicipio.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMunicipio.Modified = false;
            this.txtMunicipio.Multiline = false;
            this.txtMunicipio.Name = "txtMunicipio";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMunicipio.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMunicipio.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Silver;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMunicipio.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMunicipio.OnIdleState = stateProperties32;
            this.txtMunicipio.Padding = new System.Windows.Forms.Padding(3);
            this.txtMunicipio.PasswordChar = '\0';
            this.txtMunicipio.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtMunicipio.PlaceholderText = "Municipio";
            this.txtMunicipio.ReadOnly = false;
            this.txtMunicipio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMunicipio.SelectedText = "";
            this.txtMunicipio.SelectionLength = 0;
            this.txtMunicipio.SelectionStart = 0;
            this.txtMunicipio.ShortcutsEnabled = true;
            this.txtMunicipio.Size = new System.Drawing.Size(217, 43);
            this.txtMunicipio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMunicipio.TabIndex = 315;
            this.txtMunicipio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMunicipio.TextMarginBottom = 0;
            this.txtMunicipio.TextMarginLeft = 3;
            this.txtMunicipio.TextMarginTop = 0;
            this.txtMunicipio.TextPlaceholder = "Municipio";
            this.txtMunicipio.UseSystemPasswordChar = false;
            this.txtMunicipio.WordWrap = true;
            // 
            // txtCalle
            // 
            this.txtCalle.AcceptsReturn = false;
            this.txtCalle.AcceptsTab = false;
            this.txtCalle.AnimationSpeed = 200;
            this.txtCalle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCalle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCalle.BackColor = System.Drawing.Color.Transparent;
            this.txtCalle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCalle.BackgroundImage")));
            this.txtCalle.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtCalle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCalle.BorderColorHover = System.Drawing.Color.Silver;
            this.txtCalle.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCalle.BorderRadius = 20;
            this.txtCalle.BorderThickness = 1;
            this.txtCalle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCalle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalle.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCalle.DefaultText = "";
            this.txtCalle.FillColor = System.Drawing.Color.White;
            this.txtCalle.HideSelection = true;
            this.txtCalle.IconLeft = null;
            this.txtCalle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalle.IconPadding = 10;
            this.txtCalle.IconRight = null;
            this.txtCalle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalle.Lines = new string[0];
            this.txtCalle.Location = new System.Drawing.Point(247, 257);
            this.txtCalle.MaxLength = 32767;
            this.txtCalle.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCalle.Modified = false;
            this.txtCalle.Multiline = false;
            this.txtCalle.Name = "txtCalle";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalle.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCalle.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Silver;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalle.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalle.OnIdleState = stateProperties36;
            this.txtCalle.Padding = new System.Windows.Forms.Padding(3);
            this.txtCalle.PasswordChar = '\0';
            this.txtCalle.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtCalle.PlaceholderText = "Calle y num";
            this.txtCalle.ReadOnly = false;
            this.txtCalle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCalle.SelectedText = "";
            this.txtCalle.SelectionLength = 0;
            this.txtCalle.SelectionStart = 0;
            this.txtCalle.ShortcutsEnabled = true;
            this.txtCalle.Size = new System.Drawing.Size(217, 43);
            this.txtCalle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCalle.TabIndex = 314;
            this.txtCalle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCalle.TextMarginBottom = 0;
            this.txtCalle.TextMarginLeft = 3;
            this.txtCalle.TextMarginTop = 0;
            this.txtCalle.TextPlaceholder = "Calle y num";
            this.txtCalle.UseSystemPasswordChar = false;
            this.txtCalle.WordWrap = true;
            // 
            // txtEstado
            // 
            this.txtEstado.AcceptsReturn = false;
            this.txtEstado.AcceptsTab = false;
            this.txtEstado.AnimationSpeed = 200;
            this.txtEstado.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEstado.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEstado.BackColor = System.Drawing.Color.Transparent;
            this.txtEstado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEstado.BackgroundImage")));
            this.txtEstado.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtEstado.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEstado.BorderColorHover = System.Drawing.Color.Silver;
            this.txtEstado.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEstado.BorderRadius = 20;
            this.txtEstado.BorderThickness = 1;
            this.txtEstado.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEstado.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEstado.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEstado.DefaultText = "";
            this.txtEstado.FillColor = System.Drawing.Color.White;
            this.txtEstado.HideSelection = true;
            this.txtEstado.IconLeft = null;
            this.txtEstado.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEstado.IconPadding = 10;
            this.txtEstado.IconRight = null;
            this.txtEstado.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEstado.Lines = new string[0];
            this.txtEstado.Location = new System.Drawing.Point(767, 257);
            this.txtEstado.MaxLength = 32767;
            this.txtEstado.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEstado.Modified = false;
            this.txtEstado.Multiline = false;
            this.txtEstado.Name = "txtEstado";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEstado.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEstado.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Silver;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEstado.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEstado.OnIdleState = stateProperties28;
            this.txtEstado.Padding = new System.Windows.Forms.Padding(3);
            this.txtEstado.PasswordChar = '\0';
            this.txtEstado.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtEstado.PlaceholderText = "Estado";
            this.txtEstado.ReadOnly = false;
            this.txtEstado.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEstado.SelectedText = "";
            this.txtEstado.SelectionLength = 0;
            this.txtEstado.SelectionStart = 0;
            this.txtEstado.ShortcutsEnabled = true;
            this.txtEstado.Size = new System.Drawing.Size(217, 43);
            this.txtEstado.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEstado.TabIndex = 316;
            this.txtEstado.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEstado.TextMarginBottom = 0;
            this.txtEstado.TextMarginLeft = 3;
            this.txtEstado.TextMarginTop = 0;
            this.txtEstado.TextPlaceholder = "Estado";
            this.txtEstado.UseSystemPasswordChar = false;
            this.txtEstado.WordWrap = true;
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = false;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.Silver;
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefono.BorderRadius = 20;
            this.txtTelefono.BorderThickness = 1;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.White;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(767, 319);
            this.txtTelefono.MaxLength = 32767;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefono.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Silver;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties16;
            this.txtTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtTelefono.PlaceholderText = "Teléfono";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = true;
            this.txtTelefono.Size = new System.Drawing.Size(217, 43);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefono.TabIndex = 319;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 3;
            this.txtTelefono.TextMarginTop = 0;
            this.txtTelefono.TextPlaceholder = "Teléfono";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            this.txtTelefono.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.SoloNumeros_KeyPress);
            // 
            // txtCp
            // 
            this.txtCp.AcceptsReturn = false;
            this.txtCp.AcceptsTab = false;
            this.txtCp.AnimationSpeed = 200;
            this.txtCp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCp.BackColor = System.Drawing.Color.Transparent;
            this.txtCp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCp.BackgroundImage")));
            this.txtCp.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtCp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCp.BorderColorHover = System.Drawing.Color.Silver;
            this.txtCp.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCp.BorderRadius = 20;
            this.txtCp.BorderThickness = 1;
            this.txtCp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCp.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCp.DefaultText = "";
            this.txtCp.FillColor = System.Drawing.Color.White;
            this.txtCp.HideSelection = true;
            this.txtCp.IconLeft = null;
            this.txtCp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCp.IconPadding = 10;
            this.txtCp.IconRight = null;
            this.txtCp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCp.Lines = new string[0];
            this.txtCp.Location = new System.Drawing.Point(505, 319);
            this.txtCp.MaxLength = 32767;
            this.txtCp.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCp.Modified = false;
            this.txtCp.Multiline = false;
            this.txtCp.Name = "txtCp";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCp.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCp.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Silver;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCp.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCp.OnIdleState = stateProperties20;
            this.txtCp.Padding = new System.Windows.Forms.Padding(3);
            this.txtCp.PasswordChar = '\0';
            this.txtCp.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtCp.PlaceholderText = "C.P";
            this.txtCp.ReadOnly = false;
            this.txtCp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCp.SelectedText = "";
            this.txtCp.SelectionLength = 0;
            this.txtCp.SelectionStart = 0;
            this.txtCp.ShortcutsEnabled = true;
            this.txtCp.Size = new System.Drawing.Size(217, 43);
            this.txtCp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCp.TabIndex = 318;
            this.txtCp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCp.TextMarginBottom = 0;
            this.txtCp.TextMarginLeft = 3;
            this.txtCp.TextMarginTop = 0;
            this.txtCp.TextPlaceholder = "C.P";
            this.txtCp.UseSystemPasswordChar = false;
            this.txtCp.WordWrap = true;
            this.txtCp.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.SoloNumeros_KeyPress);
            // 
            // txtPais
            // 
            this.txtPais.AcceptsReturn = false;
            this.txtPais.AcceptsTab = false;
            this.txtPais.AnimationSpeed = 200;
            this.txtPais.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPais.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPais.BackColor = System.Drawing.Color.Transparent;
            this.txtPais.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPais.BackgroundImage")));
            this.txtPais.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtPais.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPais.BorderColorHover = System.Drawing.Color.Silver;
            this.txtPais.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPais.BorderRadius = 20;
            this.txtPais.BorderThickness = 1;
            this.txtPais.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPais.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPais.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPais.DefaultText = "";
            this.txtPais.FillColor = System.Drawing.Color.White;
            this.txtPais.HideSelection = true;
            this.txtPais.IconLeft = null;
            this.txtPais.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPais.IconPadding = 10;
            this.txtPais.IconRight = null;
            this.txtPais.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPais.Lines = new string[0];
            this.txtPais.Location = new System.Drawing.Point(247, 319);
            this.txtPais.MaxLength = 32767;
            this.txtPais.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPais.Modified = false;
            this.txtPais.Multiline = false;
            this.txtPais.Name = "txtPais";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPais.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPais.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Silver;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPais.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPais.OnIdleState = stateProperties24;
            this.txtPais.Padding = new System.Windows.Forms.Padding(3);
            this.txtPais.PasswordChar = '\0';
            this.txtPais.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtPais.PlaceholderText = "País";
            this.txtPais.ReadOnly = false;
            this.txtPais.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPais.SelectedText = "";
            this.txtPais.SelectionLength = 0;
            this.txtPais.SelectionStart = 0;
            this.txtPais.ShortcutsEnabled = true;
            this.txtPais.Size = new System.Drawing.Size(217, 43);
            this.txtPais.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPais.TabIndex = 317;
            this.txtPais.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPais.TextMarginBottom = 0;
            this.txtPais.TextMarginLeft = 3;
            this.txtPais.TextMarginTop = 0;
            this.txtPais.TextPlaceholder = "País";
            this.txtPais.UseSystemPasswordChar = false;
            this.txtPais.WordWrap = true;
            // 
            // txtCorreo
            // 
            this.txtCorreo.AcceptsReturn = false;
            this.txtCorreo.AcceptsTab = false;
            this.txtCorreo.AnimationSpeed = 200;
            this.txtCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCorreo.BackgroundImage")));
            this.txtCorreo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCorreo.BorderColorHover = System.Drawing.Color.Silver;
            this.txtCorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCorreo.BorderRadius = 20;
            this.txtCorreo.BorderThickness = 1;
            this.txtCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCorreo.DefaultText = "";
            this.txtCorreo.FillColor = System.Drawing.Color.White;
            this.txtCorreo.HideSelection = true;
            this.txtCorreo.IconLeft = null;
            this.txtCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.IconPadding = 10;
            this.txtCorreo.IconRight = null;
            this.txtCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.Lines = new string[0];
            this.txtCorreo.Location = new System.Drawing.Point(247, 381);
            this.txtCorreo.MaxLength = 32767;
            this.txtCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCorreo.Modified = false;
            this.txtCorreo.Multiline = false;
            this.txtCorreo.Name = "txtCorreo";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCorreo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Silver;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnIdleState = stateProperties12;
            this.txtCorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtCorreo.PasswordChar = '\0';
            this.txtCorreo.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtCorreo.PlaceholderText = "Correo electrónico";
            this.txtCorreo.ReadOnly = false;
            this.txtCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCorreo.SelectedText = "";
            this.txtCorreo.SelectionLength = 0;
            this.txtCorreo.SelectionStart = 0;
            this.txtCorreo.ShortcutsEnabled = true;
            this.txtCorreo.Size = new System.Drawing.Size(737, 43);
            this.txtCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCorreo.TabIndex = 320;
            this.txtCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCorreo.TextMarginBottom = 0;
            this.txtCorreo.TextMarginLeft = 3;
            this.txtCorreo.TextMarginTop = 0;
            this.txtCorreo.TextPlaceholder = "Correo electrónico";
            this.txtCorreo.UseSystemPasswordChar = false;
            this.txtCorreo.WordWrap = true;
            // 
            // bunifuShapes3
            // 
            this.bunifuShapes3.Angle = 0F;
            this.bunifuShapes3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes3.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes3.BorderThickness = 2;
            this.bunifuShapes3.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes3.FillShape = true;
            this.bunifuShapes3.Location = new System.Drawing.Point(247, 468);
            this.bunifuShapes3.Name = "bunifuShapes3";
            this.bunifuShapes3.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes3.Sides = 5;
            this.bunifuShapes3.Size = new System.Drawing.Size(765, 12);
            this.bunifuShapes3.TabIndex = 322;
            this.bunifuShapes3.Text = "bunifuShapes3";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Segoe UI Black", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label3.Location = new System.Drawing.Point(243, 449);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(157, 23);
            this.label3.TabIndex = 321;
            this.label3.Text = "Acceso al sistema";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // cboTurno
            // 
            this.cboTurno.BackColor = System.Drawing.Color.Transparent;
            this.cboTurno.BackgroundColor = System.Drawing.Color.White;
            this.cboTurno.BorderColor = System.Drawing.Color.Silver;
            this.cboTurno.BorderRadius = 10;
            this.cboTurno.Color = System.Drawing.Color.Silver;
            this.cboTurno.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cboTurno.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboTurno.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cboTurno.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboTurno.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cboTurno.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cboTurno.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cboTurno.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cboTurno.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTurno.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboTurno.FillDropDown = true;
            this.cboTurno.FillIndicator = false;
            this.cboTurno.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboTurno.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cboTurno.ForeColor = System.Drawing.Color.Black;
            this.cboTurno.FormattingEnabled = true;
            this.cboTurno.Icon = null;
            this.cboTurno.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboTurno.IndicatorColor = System.Drawing.Color.Gray;
            this.cboTurno.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboTurno.ItemBackColor = System.Drawing.Color.White;
            this.cboTurno.ItemBorderColor = System.Drawing.Color.White;
            this.cboTurno.ItemForeColor = System.Drawing.Color.Black;
            this.cboTurno.ItemHeight = 37;
            this.cboTurno.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.cboTurno.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cboTurno.Items.AddRange(new object[] {
            "-- Turno --",
            "Matutino",
            "Vespertino"});
            this.cboTurno.ItemTopMargin = 3;
            this.cboTurno.Location = new System.Drawing.Point(247, 499);
            this.cboTurno.Name = "cboTurno";
            this.cboTurno.Size = new System.Drawing.Size(349, 43);
            this.cboTurno.TabIndex = 323;
            this.cboTurno.Text = null;
            this.cboTurno.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboTurno.TextLeftMargin = 5;
            // 
            // cboRol
            // 
            this.cboRol.BackColor = System.Drawing.Color.Transparent;
            this.cboRol.BackgroundColor = System.Drawing.Color.White;
            this.cboRol.BorderColor = System.Drawing.Color.Silver;
            this.cboRol.BorderRadius = 10;
            this.cboRol.Color = System.Drawing.Color.Silver;
            this.cboRol.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cboRol.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboRol.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cboRol.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboRol.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cboRol.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cboRol.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cboRol.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cboRol.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboRol.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboRol.FillDropDown = true;
            this.cboRol.FillIndicator = false;
            this.cboRol.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboRol.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cboRol.ForeColor = System.Drawing.Color.Black;
            this.cboRol.FormattingEnabled = true;
            this.cboRol.Icon = null;
            this.cboRol.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboRol.IndicatorColor = System.Drawing.Color.Gray;
            this.cboRol.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboRol.ItemBackColor = System.Drawing.Color.White;
            this.cboRol.ItemBorderColor = System.Drawing.Color.White;
            this.cboRol.ItemForeColor = System.Drawing.Color.Black;
            this.cboRol.ItemHeight = 37;
            this.cboRol.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.cboRol.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cboRol.Items.AddRange(new object[] {
            "Empleado",
            "Administrador"});
            this.cboRol.ItemTopMargin = 3;
            this.cboRol.Location = new System.Drawing.Point(635, 499);
            this.cboRol.Name = "cboRol";
            this.cboRol.Size = new System.Drawing.Size(349, 43);
            this.cboRol.TabIndex = 324;
            this.cboRol.Text = null;
            this.cboRol.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboRol.TextLeftMargin = 5;
            // 
            // txtUsuario
            // 
            this.txtUsuario.AcceptsReturn = false;
            this.txtUsuario.AcceptsTab = false;
            this.txtUsuario.AnimationSpeed = 200;
            this.txtUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsuario.BackColor = System.Drawing.Color.Transparent;
            this.txtUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsuario.BackgroundImage")));
            this.txtUsuario.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsuario.BorderColorHover = System.Drawing.Color.Silver;
            this.txtUsuario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsuario.BorderRadius = 20;
            this.txtUsuario.BorderThickness = 1;
            this.txtUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUsuario.DefaultText = "";
            this.txtUsuario.FillColor = System.Drawing.Color.White;
            this.txtUsuario.HideSelection = true;
            this.txtUsuario.IconLeft = null;
            this.txtUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.IconPadding = 10;
            this.txtUsuario.IconRight = null;
            this.txtUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.Lines = new string[0];
            this.txtUsuario.Location = new System.Drawing.Point(247, 563);
            this.txtUsuario.MaxLength = 32767;
            this.txtUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsuario.Modified = false;
            this.txtUsuario.Multiline = false;
            this.txtUsuario.Name = "txtUsuario";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Silver;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnIdleState = stateProperties8;
            this.txtUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsuario.PasswordChar = '\0';
            this.txtUsuario.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtUsuario.PlaceholderText = "Usuario";
            this.txtUsuario.ReadOnly = false;
            this.txtUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsuario.SelectedText = "";
            this.txtUsuario.SelectionLength = 0;
            this.txtUsuario.SelectionStart = 0;
            this.txtUsuario.ShortcutsEnabled = true;
            this.txtUsuario.Size = new System.Drawing.Size(349, 43);
            this.txtUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsuario.TabIndex = 325;
            this.txtUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsuario.TextMarginBottom = 0;
            this.txtUsuario.TextMarginLeft = 3;
            this.txtUsuario.TextMarginTop = 0;
            this.txtUsuario.TextPlaceholder = "Usuario";
            this.txtUsuario.UseSystemPasswordChar = false;
            this.txtUsuario.WordWrap = true;
            // 
            // txtContrasena
            // 
            this.txtContrasena.AcceptsReturn = false;
            this.txtContrasena.AcceptsTab = false;
            this.txtContrasena.AnimationSpeed = 200;
            this.txtContrasena.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContrasena.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContrasena.BackColor = System.Drawing.Color.Transparent;
            this.txtContrasena.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContrasena.BackgroundImage")));
            this.txtContrasena.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.txtContrasena.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContrasena.BorderColorHover = System.Drawing.Color.Silver;
            this.txtContrasena.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtContrasena.BorderRadius = 20;
            this.txtContrasena.BorderThickness = 1;
            this.txtContrasena.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContrasena.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContrasena.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContrasena.DefaultText = "";
            this.txtContrasena.FillColor = System.Drawing.Color.White;
            this.txtContrasena.HideSelection = true;
            this.txtContrasena.IconLeft = null;
            this.txtContrasena.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContrasena.IconPadding = 10;
            this.txtContrasena.IconRight = null;
            this.txtContrasena.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContrasena.Lines = new string[0];
            this.txtContrasena.Location = new System.Drawing.Point(635, 563);
            this.txtContrasena.MaxLength = 32767;
            this.txtContrasena.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtContrasena.Modified = false;
            this.txtContrasena.Multiline = false;
            this.txtContrasena.Name = "txtContrasena";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContrasena.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContrasena.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Silver;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContrasena.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContrasena.OnIdleState = stateProperties4;
            this.txtContrasena.Padding = new System.Windows.Forms.Padding(3);
            this.txtContrasena.PasswordChar = '●';
            this.txtContrasena.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txtContrasena.PlaceholderText = "Nombre";
            this.txtContrasena.ReadOnly = false;
            this.txtContrasena.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContrasena.SelectedText = "";
            this.txtContrasena.SelectionLength = 0;
            this.txtContrasena.SelectionStart = 0;
            this.txtContrasena.ShortcutsEnabled = true;
            this.txtContrasena.Size = new System.Drawing.Size(349, 43);
            this.txtContrasena.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContrasena.TabIndex = 326;
            this.txtContrasena.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContrasena.TextMarginBottom = 0;
            this.txtContrasena.TextMarginLeft = 3;
            this.txtContrasena.TextMarginTop = 0;
            this.txtContrasena.TextPlaceholder = "Nombre";
            this.txtContrasena.UseSystemPasswordChar = true;
            this.txtContrasena.WordWrap = true;
            // 
            // btnGuardar
            // 
            this.btnGuardar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(67)))), ((int)(((byte)(21)))));
            this.btnGuardar.FlatAppearance.BorderSize = 0;
            this.btnGuardar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconChar = FontAwesome.Sharp.MaterialIcons.Floppy;
            this.btnGuardar.IconColor = System.Drawing.Color.White;
            this.btnGuardar.IconSize = 40;
            this.btnGuardar.Location = new System.Drawing.Point(836, 642);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(148, 43);
            this.btnGuardar.TabIndex = 327;
            this.btnGuardar.Text = "Guardar";
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnGuardar.UseVisualStyleBackColor = false;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            // 
            // bunifuElipse2
            // 
            this.bunifuElipse2.ElipseRadius = 15;
            this.bunifuElipse2.TargetControl = this.btnGuardar;
            // 
            // btnCancelar
            // 
            this.btnCancelar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(31)))), ((int)(((byte)(31)))));
            this.btnCancelar.FlatAppearance.BorderSize = 0;
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.IconChar = FontAwesome.Sharp.MaterialIcons.WindowClose;
            this.btnCancelar.IconColor = System.Drawing.Color.White;
            this.btnCancelar.IconSize = 40;
            this.btnCancelar.Location = new System.Drawing.Point(666, 642);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(148, 43);
            this.btnCancelar.TabIndex = 328;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnCancelar.UseVisualStyleBackColor = false;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            // 
            // bunifuElipse3
            // 
            this.bunifuElipse3.ElipseRadius = 15;
            this.bunifuElipse3.TargetControl = this.btnCancelar;
            // 
            // pictureEmpleado
            // 
            this.pictureEmpleado.AllowFocused = false;
            this.pictureEmpleado.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pictureEmpleado.AutoSizeHeight = true;
            this.pictureEmpleado.BorderRadius = 85;
            this.pictureEmpleado.Image = ((System.Drawing.Image)(resources.GetObject("pictureEmpleado.Image")));
            this.pictureEmpleado.IsCircle = true;
            this.pictureEmpleado.Location = new System.Drawing.Point(32, 95);
            this.pictureEmpleado.Name = "pictureEmpleado";
            this.pictureEmpleado.Size = new System.Drawing.Size(170, 170);
            this.pictureEmpleado.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureEmpleado.TabIndex = 329;
            this.pictureEmpleado.TabStop = false;
            this.pictureEmpleado.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.pictureEmpleado.DoubleClick += new System.EventHandler(this.pictureEmpleado_DoubleClick);
            // 
            // frmReEdEmpleados
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1038, 697);
            this.Controls.Add(this.pictureEmpleado);
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.txtContrasena);
            this.Controls.Add(this.txtUsuario);
            this.Controls.Add(this.cboRol);
            this.Controls.Add(this.cboTurno);
            this.Controls.Add(this.bunifuShapes3);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtCorreo);
            this.Controls.Add(this.txtTelefono);
            this.Controls.Add(this.txtCp);
            this.Controls.Add(this.txtPais);
            this.Controls.Add(this.txtEstado);
            this.Controls.Add(this.txtMunicipio);
            this.Controls.Add(this.txtCalle);
            this.Controls.Add(this.btnCerrar);
            this.Controls.Add(this.bunifuShapes2);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.dtpFechaNacimiento);
            this.Controls.Add(this.txtApellidos);
            this.Controls.Add(this.txtNombre);
            this.Controls.Add(this.bunifuShapes1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.materialPictureBox2);
            this.Controls.Add(this.lblUsuario);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmReEdEmpleados";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmReEdEmpleados";
            this.Load += new System.EventHandler(this.frmReEdEmpleados_Load);
            ((System.ComponentModel.ISupportInitialize)(this.materialPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEmpleado)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private FontAwesome.Sharp.Material.MaterialPictureBox materialPictureBox2;
        private System.Windows.Forms.Label lblUsuario;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes2;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuDatePicker dtpFechaNacimiento;
        private Bunifu.UI.WinForms.BunifuTextBox txtApellidos;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        private FontAwesome.Sharp.Material.MaterialButton btnCerrar;
        private Bunifu.UI.WinForms.BunifuTextBox txtCorreo;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefono;
        private Bunifu.UI.WinForms.BunifuTextBox txtCp;
        private Bunifu.UI.WinForms.BunifuTextBox txtPais;
        private Bunifu.UI.WinForms.BunifuTextBox txtEstado;
        private Bunifu.UI.WinForms.BunifuTextBox txtMunicipio;
        private Bunifu.UI.WinForms.BunifuTextBox txtCalle;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes3;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtContrasena;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsuario;
        private Bunifu.UI.WinForms.BunifuDropdown cboRol;
        private Bunifu.UI.WinForms.BunifuDropdown cboTurno;
        private FontAwesome.Sharp.Material.MaterialButton btnCancelar;
        private FontAwesome.Sharp.Material.MaterialButton btnGuardar;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse2;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse3;
        private Bunifu.UI.WinForms.BunifuPictureBox pictureEmpleado;
    }
}